In [5]:
import numpy as np

In [6]:
a= numpy.array([1,2,3])
a

array([1, 2, 3])

In [7]:
a * 3


array([3, 6, 9])

In [8]:
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

## arange, linspace, logspace

In [9]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.logspace(0,10,5)

array([1.00000000e+00, 3.16227766e+02, 1.00000000e+05, 3.16227766e+07,
       1.00000000e+10])

In [11]:
np.random.rand(4,10)

array([[0.12195481, 0.39150213, 0.43245144, 0.74992346, 0.7531481 ,
        0.69860451, 0.06741807, 0.87753347, 0.89996539, 0.99504277],
       [0.8782014 , 0.13849745, 0.78759377, 0.95768661, 0.11477692,
        0.23894148, 0.0830244 , 0.11068943, 0.73099898, 0.53231149],
       [0.02361884, 0.92459282, 0.69702155, 0.14540146, 0.62136858,
        0.8895595 , 0.71438078, 0.06682217, 0.29112852, 0.16962989],
       [0.63336338, 0.41022175, 0.79849415, 0.49372126, 0.58086302,
        0.04328295, 0.89964581, 0.47263952, 0.96014101, 0.2002318 ]])

## Controlled Randmness

In [14]:
state = np.random.RandomState(42)
state.rand(10)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
       0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])